import { Inter } from 'next/font/google'
import './globals.css'
import Authprovider from '../component/authprovider/Authprovider'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
        <Navbar/>
      
        {children}
        <Footer />
        </Authprovider>

      
        
        </body>
    </html>
  )
}
